### ISSUE TITLE
Add .gitkeep files to empty folders

### ISSUE THREAD

**Issue by ricardoebbers** [ResoCoder/flutter-tdd-clean-architecture-course#2]
Hey Matt!

I'm a big fan of your Flutter videos. I've been experimenting with Flutter for some weeks and your guides helped me a lot, thanks!

For this course, as folder structure is really important, I want to ask you if you can add .gitkeep empty files to the empty folders, so we can better follow the fundamentals of the first lesson, or even clone this repository as a template for new projects!

Thanks again and keep the excellent work!

**Comment by ResoDev** [comment]
Hello and thanks for learning here!
Thanks for informing me about this "empty folders" problem, I'll fix it ASAP.
