### ISSUE TITLE
test network_info_test (at least) does not work properly (Mock problem?)

### ISSUE THREAD

**Issue by ValeriusGC** [ResoCoder/flutter-tdd-clean-architecture-course#26]
It passed well with original
`final tHasConnectionFuture = Future.value(true);`
as well as with
`final tHasConnectionFuture = Future.value(**false**);`
How so?

**Comment by lukechi1219** [comment]
since your mockDataConnectionChecker.hasConnection
answers Future.value(false) -> result

it's correct the test passes, because result (false) is same as your final tHasConnectionFuture = Future.value(false) .

expect(result, tHasConnectionFutureFalse);
