### ISSUE TITLE
Got Error Expected: Actual

### ISSUE THREAD

**Issue by riocolis** [ResoCoder/flutter-tdd-clean-architecture-course#32]
![image](https://user-images.githubusercontent.com/35004114/97286928-8fa38d00-1876-11eb-93ba-10f55620e683.png)

i got error 
`fromJson should return a valid model when the JSON number is an integer:

ERROR: Expected: NumberTriviaModel:<NumberTriviaModel>
  Actual: NumberTriviaModel:<NumberTriviaModel>

package:test_api                                                            expect
package:flutter_test/src/widget_tester.dart 431:3                           expect
test\features\number_trivia\data\models\number_trivia_model_test.dart 30:9  main.<fn>.<fn>`

how to Resolve this ?

**Comment by riocolis** [comment]
Got it because `trivia.json` must be same at NumberTriviaModel

**Comment by Gegerout** [comment]
I got same error, but I don't undestand how to fix it
![Снимок экрана (69)](https://user-images.githubusercontent.com/72309553/221945649-6c830b24-dafa-40cd-a5b0-a390bafb1348.png)
