### ISSUE TITLE
main.dart

### ISSUE THREAD

**Issue by arnaudelub** [ResoCoder/flutter-tdd-clean-architecture-course#4]
Hi and thank you so much for those tutorials, very interesting and well explained.

Can you please update your main.dart? i'm not sure how to initiate the app.

Thanks.

**Comment by joelowrance** [comment]
Can you also add your vscode launch.json?  However you are running tests seems way less cumbersome than what I am doing.

**Comment by ResoDev** [comment]
I've just pushed the finished app, you'll just have to wait for the explanation as I still have to edit and publish the tutorials.

**Comment by ResoDev** [comment]
> Can you also add your vscode launch.json? However you are running tests seems way less cumbersome than what I am doing.

`launch.json` is already present in the `.vscode` folder and I've set up a keyboard shortcut of **Shift + Alt + [** which launches the "Dart: Run all tests" command.
