### ISSUE TITLE
type 'Null' is not a subtype of type 'Future<Either<Failure, LocalUser>>'

### ISSUE THREAD

**Issue by nazrinharris** [ResoCoder/flutter-tdd-clean-architecture-course#40]
I just changed a few things here and there and I encountered this weird problem and solution.

Full details here :-
https://stackoverflow.com/questions/67443531/flutter-using-async-in-testing-produces-an-error-but-using-async-made-it-work

**Comment by robsonsilv4** [comment]
If you're using Flutter 2:

- Upgrade dartz to ns prerelease: 0.10.0-nullsafety.2
- And replace mockito with [mocktail](https://pub.dev/packages/mocktail).

**Comment by nazrinharris** [comment]
I found the solution, which is suprising easy and I'm stupid. I havent tried using mocktail yet but using mockito is still perfectly fine as well. I just didnt generate Mock classes as stated in the mockito docs to support null safety. I also explained in the stackoverflow posts

**Comment by nanjadev** [comment]
This problem is about the Mockito version (not null safety). Upgrade your version to ^5.0.0. More about Mockito and null safety you can read [here (Mockito - NULL_SAFETY_README)](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md)


You can try mocktail as well, the example below.

      when(() => mockNumberTriviaRepository.getConcreteNumberTrivia(tNumber))
        .thenAnswer((_) async => Right(tNumberTrivia));

        final result = await usecase.execute(number: tNumber);
        expect(result, equal(Right(tNumberTrivia)));
        verify(() => mockNumberTriviaRepository.getConcreteNumberTrivia(tNumber));
        verifyNoMoreInteractions(mockNumberTriviaRepository);

**Comment by erncncbk** [comment]
The problem related  with null-safety. I faced the same problem and later on I fixed.
[You can check it](https://stackoverflow.com/a/69166883/11365757)
